using System.ComponentModel.DataAnnotations;
using PatientDocs.Models.Enums;

namespace PatientDocs.Models
{
    public class User
    {
        // Unique identifier for the user.
        // Auto-generated by the database when a new user is created.
        public int Id { get; set; }

        //user's email address, used for login and identification.
        [Required] //makes it so that the email is required
        [EmailAddress]
        [MaxLength(255)]
        public string Email { get; set; } = string.Empty; //default value is an empty string

        /// Encrypted version of the user's password.
        /// we dont wanna store plain text passesowrds. this field contains the hash.
        [Required]
        [MinLength(6)]
        [MaxLength(255)]
        public string PasswordHash { get; set; } = string.Empty;


        // User's role in the system (Admin or Doctor).
        // Controls what actions the user can perform.
        [Required]
        public UserRole Role { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
